sudo: required
language: node_js

node_js: 
  - 17

env:
  global:
    - MY_ENV_VAR=value

before_install:
  - npm i --location=global npm@8.11.0

install:
  - npm install

script:
  - npm test
  - echo $MY_ENV_VAR
  - npm run lint
