sudo: required
language: node_js

node_js: 
  - stable

env:
  global:
    - MY_ENV_VAR=value

services:
  - docker

install:
  - npm install
  - npm install puppeteer

before_install:
  - export DISPLAY=:99.0
  -sh -e /etc/init.d/xvfb start

script:
  - node logic.js &
  - npm run test

deploy:
  provider: github
  skip_cleanup: true
  on:
    branch: main
  token: $GITHUB_TOKEN
  local_dir: build

